baseURL: "https://dasanmiguelv.github.io/portfolio/"
languageCode: en-us
title: Diego Sanmiguel
theme: PaperMod

menu:
  main:
    - identifier: home
      name: About Me
      url: /
      weight: 10    
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Diego Sanmiguel"
    subtitle: Hi 👋! I’m Diego Sanmiguel. I’m passionate about the world of data and am currently focusing on becoming a data scientist. My goal is to combine my project management experience with my data science skills to address complex business challenges.
    imageUrl: "home/WhatsApp Image 2022-01-06 at 3.42.45 PM.jpeg"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:dasanmiguel31@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/diegosanmiguelvargas/"
    - name: "github"
      url: "https://github.com/dasanmiguelv"    
    - name: "cv"
      url: "https://drive.google.com/file/d/1U6Gg2RnHSCthtWLbZJBlAEI3V1WGjZty/view"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
